version: '3'


services:
  mysql:
    image: mysql:latest
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: aya
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: aya
      MYSQL_PASSWORD: p4ssw0rd1
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - ~/mysql_data:/var/lib/mysql