app:
  env: "dev"
  app_name: "dev"
  log_level: "debug"
  secret: "thisissecret"
  api_key: "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"
  web: "http://localhost:5179/dashboard"
server:
  http_address: "9000"
database:
  host: "192.168.123.30:3306"
  username: "root"
  password: "aya"
  database: "nanne"
  max_idle: 10
  max_open: 10
